proxy:
  title: ShinyProxy Example
  logo-url: https://www.example.com/logo.png
  landing-page: /
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  port: 8080
  authentication: openid
  docker:
    internal-networking: true
  specs:
  - id: admin
    container-image: registry.example.com/shinyadmin
  - id: app1
    container-image: registry.example.com/shinyapp1
  - id: app2
    container-image: registry.example.com/shinyapp2
  - id: app3
    container-image: registry.example.com/shinyapp3

logging:
  file:
    shinyproxy.log
