# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
    paths:
      - "helperDesign/**"
  pull_request:
    branches: [main, master]
    types: [opened, synchronize, reopened, review_requested, ready_for_review]
    paths:
      - "helperDesign/**"
    workflow_dispatch:

name: helperDesign - R-CMD-check

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    if: github.event.pull_request.draft == false

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: true
      matrix:
        config:
          - { os: ubuntu-latest, r: "oldrel" }
          - { os: ubuntu-latest, r: "release" }

    env:
      R_KEEP_PKG_SOURCE: yes
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

    steps:
      - name: Install cURL Headers
        run: |
          sudo apt-get update
          sudo apt-get install libcurl4-openssl-dev
          sudo ACCEPT_EULA=Y apt-get install msodbcsql18 -y
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2.2.8
        with:
          extra-packages: any::rcmdcheck
          needs: check
          working-directory: "helperDesign"

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          working-directory: "helperDesign"
